### ISSUE TITLE
Make snapshotHubMessageVersion dynamic

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-js-erc712#1]
https://github.com/openlawteam/snapshot-js-erc712/blob/snaphub-integration/utils/snapshotHub.js#L2

Is it possible to do a request to `getApiStatus` to get the actual version number before returning messages from the helpers (e.g. `buildDraftMessage`)?

**Comment by jtrein** [comment]
cc: @fforbeck

**Comment by fforbeck** [comment]
Closing this one since you already implemented it @jtrein
